name: Node CI
on: [push, pull_request]
env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [ node ]
        os: [ windows-latest, ubuntu-latest ]

    steps:
      - name: Clone repository
        uses: actions/checkout@master
        with:
          fetch-depth: 5

      - name: Set Node.js version
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: npm ci
